version: "3.9"

services:

  presentation-platform:
    build:
      context: ./bench
      dockerfile: Dockerfile
    image: presentation-platform
    container_name: presentation-platform
    restart: always
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPEN_AI_ORGANIZATION=${OPEN_AI_ORGANIZATION}
    volumes:
      - type: bind
        source: ./bench
        target: /bench